### ISSUE TITLE
504 Gateway Timeouts should be wrapped in retries

### ISSUE THREAD

**Issue by jperezlatimes** [datadesk/p2p-python#20]

**Comment by charlex** [comment]
The problem with this one @jperezlatimes is that we don't yet have logs on exactly what the server is responding with. I'm assuming it says "Gateway" in it's name, but who knows? We need a reliable string to search for and catch. In the meantime we might have to change https://github.com/datadesk/p2p-python/blob/master/p2p/__init__.py#L1082 to throw a P2PException instead of rely on the request lib's raise_for_status which just spits out generic HTTPErrors.

**Comment by charlex** [comment]
This is an example of the non-P2PException that the p2p-python wrapper spits out. You'll note that the response is not included which means we can't catch it as a P2PException. We need the needle before we start looking in the haystack.

```

Task liveblog.tasks.sync_liveblog_with_p2p with id 00b8d210-7c35-4d61-8a72-6a0e05fbc3d8 raised exception:
"HTTPError(u'504 Server Error: GATEWAY_TIMEOUT for url: https://content-api.p2p.tribuneinteractive.com/content_items/la-pol-sac-essential-politics-updates-201608.json?include[]=programmed_custom_params&include[]=web_url&content_item_state_code=all',)"


Task was called with args: (<Liveblog: Essential Politics: Legislature returns, Feinstein's husband undergoing cancer treatment>,) kwargs: {}.

The contents of the full traceback was:

Traceback (most recent call last):
  File "/apps/p2p-liveblog/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/apps/p2p-liveblog/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/apps/p2p-liveblog/repo/liveblog/tasks.py", line 68, in sync_liveblog_with_p2p
    return_response=True
  File "/apps/p2p-liveblog/repo/liveblog/api.py", line 85, in create_or_update_p2p_content_item
    "web_url",
  File "/apps/p2p-liveblog/local/lib/python2.7/site-packages/p2p/__init__.py", line 189, in get_content_item
    j = self.get("/content_items/%s.json" % (slug), query)
  File "/apps/p2p-liveblog/local/lib/python2.7/site-packages/p2p/decorators.py", line 17, in f_retry
    return f(*args, **kwargs)
  File "/apps/p2p-liveblog/local/lib/python2.7/site-packages/p2p/__init__.py", line 1101, in get
    resp_log = self._check_for_errors(resp, url)
  File "/apps/p2p-liveblog/local/lib/python2.7/site-packages/p2p/__init__.py", line 1074, in _check_for_errors
    resp.raise_for_status()
  File "/apps/p2p-liveblog/local/lib/python2.7/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 504 Server Error: GATEWAY_TIMEOUT for url: https://content-api.p2p.tribuneinteractive.com/content_items/la-pol-sac-essential-politics-updates-201608.json?include[]=programmed_custom_params&include[]=web_url&content_item_state_code=all


--
Just to let you know,
py-celery at liveblog1@ip-10-0-0-140.
```
